-- ============================================================================
-- Motor de IA de atendimento (VivaConnect) — base de conhecimento vetorizada.
--
-- knowledge_base (já existia, 15 docs) vira a fonte da IA: cada documento é
-- quebrado em trechos (knowledge_chunks) com embedding da OpenAI
-- (text-embedding-3-small, 1536 dims). A edge function ai-agent busca os
-- trechos mais parecidos com a pergunta do lead (match_knowledge_chunks) e
-- responde só com base neles.
--
-- Arquivos (PDF/planilha/DOCX/TXT) têm o texto extraído NO NAVEGADOR e salvo em
-- knowledge_base.content; o original fica no bucket privado knowledge-files.
-- Assim a edge function kb-ingest só faz chunk + embedding (sem parse pesado,
-- que estouraria o limite de CPU da edge function).
--
-- ai_lead_sessions guarda a trava "IA nunca reentra": depois do handoff pro
-- agente humano, a IA não responde mais aquele lead (lição do bot reentrando
-- no WideChat).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- ── knowledge_base: colunas de arquivo + estado da indexação ────────────────
ALTER TABLE knowledge_base
  ADD COLUMN IF NOT EXISTS file_url     text,          -- link externo (a tela já usava; coluna não existia)
  ADD COLUMN IF NOT EXISTS file_path    text,          -- caminho no bucket knowledge-files
  ADD COLUMN IF NOT EXISTS file_name    text,
  ADD COLUMN IF NOT EXISTS source_type  text NOT NULL DEFAULT 'text',   -- text | pdf | sheet | doc
  ADD COLUMN IF NOT EXISTS ai_enabled   boolean NOT NULL DEFAULT true,  -- entra (ou não) no contexto da IA
  ADD COLUMN IF NOT EXISTS index_status text NOT NULL DEFAULT 'pending',-- pending | processing | ready | error
  ADD COLUMN IF NOT EXISTS index_error  text,
  ADD COLUMN IF NOT EXISTS chunk_count  integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS indexed_at   timestamptz;

-- conteúdo editado => precisa reindexar (a tela chama kb-ingest logo depois)
CREATE OR REPLACE FUNCTION public.kb_mark_stale() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.content IS DISTINCT FROM OLD.content OR NEW.title IS DISTINCT FROM OLD.title THEN
    NEW.index_status := 'pending';
    NEW.updated_at := now();
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_kb_mark_stale ON knowledge_base;
CREATE TRIGGER trg_kb_mark_stale BEFORE UPDATE ON knowledge_base
  FOR EACH ROW EXECUTE FUNCTION public.kb_mark_stale();

-- ── trechos vetorizados ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS knowledge_chunks (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id uuid NOT NULL REFERENCES knowledge_base(id) ON DELETE CASCADE,
  chunk_index integer NOT NULL,
  content     text NOT NULL,
  embedding   extensions.vector(1536) NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS knowledge_chunks_embedding_idx
  ON knowledge_chunks USING hnsw (embedding extensions.vector_cosine_ops);

-- só edge functions (service_role) leem/escrevem trechos
ALTER TABLE knowledge_chunks ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.match_knowledge_chunks(
  query_embedding extensions.vector(1536),
  match_count     integer DEFAULT 6,
  min_similarity  double precision DEFAULT 0.25
) RETURNS TABLE (document_id uuid, title text, category text, content text, similarity double precision)
LANGUAGE sql STABLE SET search_path = public, extensions AS $$
  SELECT c.document_id, kb.title, kb.category, c.content,
         1 - (c.embedding <=> query_embedding) AS similarity
    FROM knowledge_chunks c
    JOIN knowledge_base kb ON kb.id = c.document_id
   WHERE kb.ai_enabled
     AND 1 - (c.embedding <=> query_embedding) >= min_similarity
   ORDER BY c.embedding <=> query_embedding
   LIMIT match_count;
$$;

REVOKE EXECUTE ON FUNCTION public.match_knowledge_chunks(extensions.vector, integer, double precision) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.match_knowledge_chunks(extensions.vector, integer, double precision) TO service_role;

-- ── configuração da IA (linha única, id = 1) ────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_agent_settings (
  id                   smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  enabled              boolean NOT NULL DEFAULT false,  -- liga/desliga resposta automática em produção
  agent_name           text    NOT NULL DEFAULT 'Vivi',
  system_prompt        text    NOT NULL DEFAULT
'Você é a assistente virtual de atendimento da FICV (Faculdade). Converse pelo WhatsApp com pessoas interessadas nos cursos.

Como conversar:
- Mensagens curtas, naturais e cordiais, como uma pessoa real no WhatsApp. No máximo 2 parágrafos curtos.
- Use o primeiro nome do lead quando souber.
- Responda SOMENTE com base nas informações da base de conhecimento fornecida. Se a informação não estiver lá, diga que vai confirmar com um consultor — nunca invente valores, datas, descontos ou condições.
- Faça uma pergunta por vez para entender: curso de interesse, modalidade, quando pretende começar e forma de pagamento.
- Para negrito no WhatsApp use *texto* (um asterisco).',
  handoff_instructions text    NOT NULL DEFAULT
'Transfira para um consultor humano (handoff) quando:
- o lead quiser se matricular, pedir link de pagamento, boleto ou contrato;
- pedir desconto, negociação ou condição especial;
- pedir para falar com uma pessoa;
- demonstrar irritação ou reclamação;
- fizer uma pergunta que a base de conhecimento não responde.',
  chat_model           text    NOT NULL DEFAULT 'gpt-4.1-mini',
  embedding_model      text    NOT NULL DEFAULT 'text-embedding-3-small',
  temperature          numeric NOT NULL DEFAULT 0.4,
  match_count          integer NOT NULL DEFAULT 6,
  min_similarity       numeric NOT NULL DEFAULT 0.25,
  max_ai_turns         integer NOT NULL DEFAULT 12,     -- após N respostas da IA, handoff automático
  updated_at           timestamptz NOT NULL DEFAULT now(),
  updated_by           uuid REFERENCES profiles(id) ON DELETE SET NULL
);
INSERT INTO ai_agent_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE ai_agent_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY ai_agent_settings_sel   ON ai_agent_settings FOR SELECT USING (public.is_staff());
CREATE POLICY ai_agent_settings_admin ON ai_agent_settings FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ── estado da IA por lead (trava de handoff) ────────────────────────────────
CREATE TABLE IF NOT EXISTS ai_lead_sessions (
  lead_id         integer PRIMARY KEY REFERENCES leads(id) ON DELETE CASCADE,
  status          text NOT NULL DEFAULT 'active' CHECK (status IN ('active','handed_off','disabled')),
  ai_turns        integer NOT NULL DEFAULT 0,
  handoff_reason  text,
  handoff_summary text,
  handed_off_at   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ai_lead_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY ai_lead_sessions_sel ON ai_lead_sessions FOR SELECT USING (public.is_staff());
CREATE POLICY ai_lead_sessions_upd ON ai_lead_sessions FOR UPDATE USING (public.is_staff());

-- ── bucket privado dos arquivos originais ───────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('knowledge-files', 'knowledge-files', false, 52428800)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "staff read knowledge files" ON storage.objects
  FOR SELECT TO authenticated USING (bucket_id = 'knowledge-files' AND public.is_staff());
CREATE POLICY "admin upload knowledge files" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'knowledge-files' AND public.is_admin());
CREATE POLICY "admin delete knowledge files" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id = 'knowledge-files' AND public.is_admin());
