-- ============================================================================
-- Marketing > Formulários — form builder nativo (sucede o SendPulse pra
-- captação própria). Postgres é a ÚNICA fonte — sem espelho SurrealDB (feature
-- nova, não fazia parte da migração SurrealDB -> Postgres).
-- ============================================================================

-- Fonte dedicada, pra não depender de um id "mágico" de lead_sources como o
-- fallback `source_id ?? 1` do sync-sendpulse-forms.
INSERT INTO lead_sources (name, icon, color)
SELECT 'Formulário Próprio (Site)', 'FileText', '#6366f1'
WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE name = 'Formulário Próprio (Site)');

CREATE TABLE marketing_forms (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug             text NOT NULL,
  name             text NOT NULL,
  course_id        integer REFERENCES courses(id) ON DELETE SET NULL,
  source_id        bigint NOT NULL REFERENCES lead_sources(id) ON DELETE RESTRICT,
  fields           jsonb NOT NULL DEFAULT '[]'::jsonb,   -- MarketingFormField[]
  design           jsonb NOT NULL DEFAULT '{}'::jsonb,   -- MarketingFormDesign
  post_submit      jsonb NOT NULL DEFAULT
    '{"type":"message","message":"Recebemos seus dados! Em breve entraremos em contato."}'::jsonb,
  allowed_domains  text[] NOT NULL DEFAULT '{}',         -- ex.: {cursos.ficv.edu.br,ficv.edu.br}
  lgpd_enabled     boolean NOT NULL DEFAULT true,
  lgpd_text        text DEFAULT 'Autorizo o contato e o tratamento dos meus dados conforme a LGPD.',
  ativo            boolean NOT NULL DEFAULT true,
  view_count       integer NOT NULL DEFAULT 0,
  created_by       uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_marketing_forms_slug   ON marketing_forms (slug);
CREATE INDEX        idx_marketing_forms_course ON marketing_forms (course_id);
CREATE TRIGGER trg_marketing_forms_updated_at BEFORE UPDATE ON marketing_forms
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE marketing_form_submissions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id       integer REFERENCES marketing_forms(id) ON DELETE CASCADE,
  lead_id       integer REFERENCES leads(id) ON DELETE SET NULL,
  payload       jsonb NOT NULL DEFAULT '{}'::jsonb,   -- values brutos recebidos
  utm           jsonb,
  ip            text,
  user_agent    text,
  referrer      text,
  outcome       text NOT NULL DEFAULT 'pending',      -- pending|created|updated|rejected
  reject_reason text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_mfs_form            ON marketing_form_submissions (form_id);
CREATE INDEX idx_mfs_lead            ON marketing_form_submissions (lead_id);
CREATE INDEX idx_mfs_created         ON marketing_form_submissions (created_at DESC);
CREATE INDEX idx_mfs_form_ip_created ON marketing_form_submissions (form_id, ip, created_at DESC);

-- RLS: staff só lê; admin gerencia formulários. Nenhuma policy pública de
-- insert — toda escrita (submissão pública) passa pela Edge Function com
-- service_role, que ignora RLS.
ALTER TABLE marketing_forms ENABLE ROW LEVEL SECURITY;
CREATE POLICY marketing_forms_sel   ON marketing_forms FOR SELECT USING (public.is_staff());
CREATE POLICY marketing_forms_admin ON marketing_forms FOR ALL
  USING (public.is_admin()) WITH CHECK (public.is_admin());

ALTER TABLE marketing_form_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY mfs_sel ON marketing_form_submissions FOR SELECT USING (public.is_staff());
