-- ============================================================================
-- VivaConnect (Z-PRO self-hosted, api.ficv.edu.br) — base da integração.
--
-- Roda EM PARALELO ao WideChat: nada aqui mexe no fluxo widechat-*. Tudo nasce
-- desligado (vivaconnect_settings.enabled / first_message_enabled = false).
--
-- - vivaconnect_channels: 1 linha por número/API do Z-PRO (a API é por canal).
--     purpose 'official' = WABA (entrada; responde via Modo Híbrido)
--     purpose 'pool'     = números Baileys pro contato ativo (1ª mensagem)
-- - vivaconnect_outbox: fila de envio (1ª mensagem automática, envio manual,
--     resposta da IA). O worker (vivaconnect-api action=process_outbox, cron
--     1/min) respeita janela de horário, intervalo mínimo e limite diário.
-- - vivaconnect_webhook_logs: payload BRUTO de todo webhook — o schema do Z-PRO
--     não é documentado; é daqui que a gente aprende o formato real.
-- - Mensagens do VivaConnect entram na MESMA widechat_messages (provider =
--     'vivaconnect'), assim chat do lead, badge de pendentes e score funcionam
--     sem mudar tela.
-- ============================================================================

-- ── configurações (linha única) ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vivaconnect_settings (
  id                      smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  enabled                 boolean NOT NULL DEFAULT false,  -- chave geral: webhook processa + worker envia
  base_url                text    NOT NULL DEFAULT 'https://api.ficv.edu.br',
  webhook_secret          text    NOT NULL DEFAULT encode(extensions.gen_random_bytes(18), 'hex'),
  -- 1ª mensagem automática pro lead do formulário que escolheu WhatsApp
  first_message_enabled   boolean NOT NULL DEFAULT false,
  first_message_template  text    NOT NULL DEFAULT
'Olá, {primeiro_nome}! Tudo bem? Aqui é da FICV 😊
Recebemos seu interesse{curso_trecho}. Posso te ajudar com as informações?',
  send_window_start       smallint NOT NULL DEFAULT 8  CHECK (send_window_start BETWEEN 0 AND 23),
  send_window_end         smallint NOT NULL DEFAULT 20 CHECK (send_window_end BETWEEN 1 AND 24),
  min_interval_seconds    integer  NOT NULL DEFAULT 90,  -- entre 2 envios automáticos do MESMO número
  -- aluno que chama no oficial → resposta com link do portal (via Híbrido)
  student_reply_enabled   boolean NOT NULL DEFAULT false,
  student_reply_template  text    NOT NULL DEFAULT
'Olá, {primeiro_nome}! Vi aqui que você já é aluno(a) da FICV 💙
Para suporte (financeiro, secretaria, acesso ao portal), abra seu chamado pela Central de Atendimento: https://ficv-sales.vercel.app/atendimento
Por lá o setor responsável te responde e você acompanha tudo.',
  -- não-aluno no oficial → lead + IA responde (usa ai_agent_settings.enabled também)
  ai_on_official          boolean NOT NULL DEFAULT false,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  updated_by              uuid REFERENCES profiles(id) ON DELETE SET NULL
);
INSERT INTO vivaconnect_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

ALTER TABLE vivaconnect_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY vivaconnect_settings_admin ON vivaconnect_settings
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ── canais (1 API do Z-PRO por número) ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS vivaconnect_channels (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text    NOT NULL,
  purpose         text    NOT NULL CHECK (purpose IN ('official','pool')),
  kind            text    NOT NULL DEFAULT 'baileys' CHECK (kind IN ('waba','baileys','hybrid')),
  phone           text,                       -- número do canal (só dígitos, 55DDD...)
  api_id          text    NOT NULL,           -- {apiId} da URL /v2/api/external/{apiId}
  api_token       text    NOT NULL,           -- Bearer — NUNCA selecionar no front
  zpro_whatsapp_id text,                      -- id do canal no Z-PRO (vem no webhook)
  active          boolean NOT NULL DEFAULT true,
  daily_limit     integer NOT NULL DEFAULT 40, -- 1ªs mensagens/dia (número novo: começar baixo)
  last_sent_at    timestamptz,
  last_ok_at      timestamptz,
  last_error      text,
  last_error_at   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE vivaconnect_channels ENABLE ROW LEVEL SECURITY;
CREATE POLICY vivaconnect_channels_admin ON vivaconnect_channels
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ── leads: canal preferido + número fixo do VivaConnect ─────────────────────
ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS preferred_contact       text CHECK (preferred_contact IN ('whatsapp','email','phone')),
  ADD COLUMN IF NOT EXISTS vivaconnect_channel_id  bigint REFERENCES vivaconnect_channels(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS vivaconnect_ticket_id   text,
  ADD COLUMN IF NOT EXISTS vivaconnect_contact_id  text;

CREATE INDEX IF NOT EXISTS idx_leads_fone8
  ON leads (right(regexp_replace(coalesce(telefone,''), '\D', '', 'g'), 8));

-- ── mensagens: mesma tabela do WideChat, marcada por provider ───────────────
ALTER TABLE widechat_messages
  ADD COLUMN IF NOT EXISTS provider   text NOT NULL DEFAULT 'widechat',
  ADD COLUMN IF NOT EXISTS channel_id bigint REFERENCES vivaconnect_channels(id) ON DELETE SET NULL;

-- ── log bruto do webhook ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vivaconnect_webhook_logs (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id  bigint REFERENCES vivaconnect_channels(id) ON DELETE SET NULL,
  payload     jsonb NOT NULL,
  outcome     text,          -- o que o webhook fez (stored / ignored:<motivo> / error:<msg>)
  lead_id     integer,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vc_webhook_logs_created ON vivaconnect_webhook_logs (created_at DESC);

ALTER TABLE vivaconnect_webhook_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY vivaconnect_webhook_logs_admin ON vivaconnect_webhook_logs FOR SELECT USING (public.is_admin());

-- ── fila de envio ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vivaconnect_outbox (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id       integer REFERENCES leads(id) ON DELETE CASCADE,
  channel_id    bigint REFERENCES vivaconnect_channels(id) ON DELETE SET NULL, -- null = escolher do pool
  kind          text NOT NULL CHECK (kind IN ('first_message','student_reply','ai_reply','manual')),
  number        text NOT NULL,           -- destino, só dígitos
  body          text NOT NULL,
  status        text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sending','sent','failed','cancelled')),
  attempts      integer NOT NULL DEFAULT 0,
  external_key  text NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  response      jsonb,
  error         text,
  created_by    uuid REFERENCES profiles(id) ON DELETE SET NULL,
  scheduled_at  timestamptz NOT NULL DEFAULT now(),
  sent_at       timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vc_outbox_queue ON vivaconnect_outbox (status, scheduled_at) WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS idx_vc_outbox_channel_sent ON vivaconnect_outbox (channel_id, sent_at) WHERE status = 'sent';
-- 1 primeira mensagem por lead, nunca duas
CREATE UNIQUE INDEX IF NOT EXISTS uq_vc_outbox_first_message ON vivaconnect_outbox (lead_id)
  WHERE kind = 'first_message' AND status <> 'cancelled';

ALTER TABLE vivaconnect_outbox ENABLE ROW LEVEL SECURITY;
CREATE POLICY vivaconnect_outbox_sel ON vivaconnect_outbox FOR SELECT USING (public.is_staff());
CREATE POLICY vivaconnect_outbox_admin ON vivaconnect_outbox
  FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ── saúde dos canais (sem o token) ──────────────────────────────────────────
CREATE OR REPLACE VIEW vivaconnect_channel_health
WITH (security_invoker = true) AS
SELECT c.id, c.name, c.purpose, c.kind, c.phone, c.api_id, c.zpro_whatsapp_id, c.active, c.daily_limit,
       c.last_sent_at, c.last_ok_at, c.last_error, c.last_error_at, c.created_at,
       (SELECT count(*) FROM vivaconnect_outbox o
         WHERE o.channel_id = c.id AND o.status = 'sent' AND o.kind = 'first_message'
           AND o.sent_at >= date_trunc('day', now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo'
       )::int AS first_sent_today,
       (SELECT count(*) FROM vivaconnect_outbox o
         WHERE o.channel_id = c.id AND o.status = 'failed' AND o.created_at > now() - interval '24 hours'
       )::int AS failed_24h,
       (SELECT count(*) FROM leads l WHERE l.vivaconnect_channel_id = c.id)::int AS leads_fixed,
       (c.api_token IS NOT NULL AND c.api_token <> '') AS has_token
  FROM vivaconnect_channels c;

-- ── escolhe o número do pool: ativo, abaixo do limite, menos usado hoje ─────
CREATE OR REPLACE FUNCTION public.vivaconnect_pick_pool_channel()
RETURNS bigint LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT h.id
    FROM vivaconnect_channel_health h
   WHERE h.purpose = 'pool' AND h.active AND h.has_token
     AND h.first_sent_today < h.daily_limit
   ORDER BY h.first_sent_today, h.last_sent_at NULLS FIRST
   LIMIT 1;
$$;
REVOKE EXECUTE ON FUNCTION public.vivaconnect_pick_pool_channel() FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.vivaconnect_pick_pool_channel() TO service_role;

-- ── lead novo que escolheu WhatsApp → enfileira a 1ª mensagem ───────────────
CREATE OR REPLACE FUNCTION public.vivaconnect_enqueue_first_message()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  s      vivaconnect_settings;
  digits text := regexp_replace(coalesce(NEW.telefone,''), '\D', '', 'g');
  first  text := initcap(split_part(trim(coalesce(NEW.nome_completo,'')), ' ', 1));
  curso  text;
  msg    text;
BEGIN
  IF NEW.preferred_contact IS DISTINCT FROM 'whatsapp' THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND OLD.preferred_contact IS NOT DISTINCT FROM 'whatsapp' THEN RETURN NEW; END IF;
  SELECT * INTO s FROM vivaconnect_settings WHERE id = 1;
  IF NOT (s.enabled AND s.first_message_enabled) THEN RETURN NEW; END IF;
  IF length(digits) < 10 OR digits ~ '^0+$' THEN RETURN NEW; END IF;
  IF length(digits) IN (10, 11) THEN digits := '55' || digits; END IF;

  SELECT name INTO curso FROM courses WHERE id = NEW.curso_interesse;
  msg := replace(replace(replace(s.first_message_template,
           '{primeiro_nome}', coalesce(nullif(first,''), 'tudo bem')),
           '{curso_trecho}',  CASE WHEN curso IS NOT NULL THEN ' no curso de ' || curso ELSE '' END),
           '{curso}',         coalesce(curso, ''));

  INSERT INTO vivaconnect_outbox (lead_id, channel_id, kind, number, body)
  VALUES (NEW.id, NEW.vivaconnect_channel_id, 'first_message', digits, msg)
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_vivaconnect_first_message ON leads;
CREATE TRIGGER trg_vivaconnect_first_message
  AFTER INSERT OR UPDATE OF preferred_contact ON leads
  FOR EACH ROW EXECUTE FUNCTION public.vivaconnect_enqueue_first_message();

-- origem dos leads que nascem pelo VivaConnect
INSERT INTO lead_sources (name)
SELECT 'WhatsApp (VivaConnect)' WHERE NOT EXISTS (SELECT 1 FROM lead_sources WHERE name = 'WhatsApp (VivaConnect)');

-- worker da fila (1/min). Reaproveita o header de auth do cron do SendPulse.
DO $$
DECLARE auth text;
BEGIN
  SELECT substring(command from 'Bearer [A-Za-z0-9._-]+') INTO auth FROM cron.job WHERE jobname = 'sync-sendpulse-forms';
  PERFORM cron.unschedule('vivaconnect-process-outbox') WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname='vivaconnect-process-outbox');
  PERFORM cron.schedule('vivaconnect-process-outbox', '* * * * *', format(
    $c$SELECT net.http_post(url := 'https://jsswkmybkgoxpncnxgdd.supabase.co/functions/v1/vivaconnect-api', headers := jsonb_build_object('Content-Type','application/json','Authorization',%L), body := '{"action":"process_outbox"}'::jsonb, timeout_milliseconds := 55000)$c$, auth));
END $$;
