-- ============================================================================
-- BASELINE — projeto CRM-FICV (jsswkmybkgoxpncnxgdd)
-- Reconstrói o schema a partir de: OpenAPI do projeto antigo (tipos reais),
-- migrations da era Surreal (_archive_surreal_era/), e scan do SurrealDB.
-- Migração SurrealDB -> Supabase, 2026-09.
-- ============================================================================

-- ── Extensões ───────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"  WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto     WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS unaccent     WITH SCHEMA public;      -- normalize_name() depende
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- ── Enums (módulo tickets) ──────────────────────────────────────────────────
DO $$ BEGIN
  CREATE TYPE ticket_categoria AS ENUM
    ('financeiro','academico','secretaria','suporte_tecnico','certificado','cancelamento','outros');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE ticket_status AS ENUM
    ('aberto','em_atendimento','aguardando_aluno','resolvido','fechado');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TYPE ticket_prioridade AS ENUM ('baixa','media','alta','urgente');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── Helper: updated_at ──────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

-- ============================================================================
-- TABELAS DE REFERÊNCIA / LOOKUP
-- ============================================================================
CREATE TABLE stages (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  "order"      integer,
  title_color  text,
  bg_color     text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE courses (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  type          text,
  default_value numeric,
  pixel_code    text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE lead_sources (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  icon       text,
  color      text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE motivos_perda (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  motivo     text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE teams (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL,
  description text,
  color       text DEFAULT '#5551FF',
  icon        text DEFAULT '👥',
  active      boolean DEFAULT true,
  created_at  timestamp NOT NULL DEFAULT now(),
  updated_at  timestamp NOT NULL DEFAULT now()
);

-- ============================================================================
-- PROFILES  (1:1 com auth.users — staff)
-- ============================================================================
CREATE TABLE profiles (
  id         uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name  text,
  email      text,
  role       text NOT NULL DEFAULT 'agent',   -- 'admin' | 'agent'
  avatar_url text,
  score      double precision DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- ============================================================================
-- ALUNOS  (1:1 com auth.users — estudantes)
-- ============================================================================
CREATE TABLE alunos (
  id         uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  cpf        text,
  nome       text,
  email      text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_alunos_updated_at BEFORE UPDATE ON alunos
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================================
-- LEADS  (núcleo do CRM — id inteiro sequencial)
-- ============================================================================
CREATE TABLE leads (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_completo          text,
  email                  text,
  telefone               text,
  curso_interesse        integer REFERENCES courses(id) ON DELETE SET NULL,
  fonte_lead             text,
  data_entrada           timestamptz NOT NULL DEFAULT now(),
  valor_oportunidade     numeric DEFAULT 0,
  observacoes            text,
  responsavel            uuid REFERENCES profiles(id) ON DELETE SET NULL,
  stage_id               integer REFERENCES stages(id) ON DELETE SET NULL,
  tags                   text[],
  stage_entry_date       timestamptz DEFAULT now(),
  temperatura            text DEFAULT 'frio',
  assigned_to_id         uuid REFERENCES profiles(id) ON DELETE SET NULL,
  source_id              bigint REFERENCES lead_sources(id) ON DELETE SET NULL,
  motivo_perda_id        bigint REFERENCES motivos_perda(id) ON DELETE SET NULL,
  contact_count          integer DEFAULT 1,
  curso_interesse_nome   text,
  widechat_contact_id    text,
  widechat_session_id    text,
  widechat_attendance_id text,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_leads_assigned     ON leads (assigned_to_id);
CREATE INDEX idx_leads_stage        ON leads (stage_id);
CREATE INDEX idx_leads_email        ON leads (email);
CREATE INDEX idx_leads_telefone     ON leads (telefone);
CREATE INDEX idx_leads_widechat     ON leads (widechat_contact_id);
CREATE INDEX idx_leads_data_entrada ON leads (data_entrada DESC);
CREATE TRIGGER trg_leads_updated_at BEFORE UPDATE ON leads
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE lead_notes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id    integer NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  note       text,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_lead_notes_lead ON lead_notes (lead_id);

CREATE TABLE lead_history (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id       integer NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  from_stage_id integer REFERENCES stages(id) ON DELETE SET NULL,
  to_stage_id   integer REFERENCES stages(id) ON DELETE SET NULL,
  changed_by    uuid REFERENCES profiles(id) ON DELETE SET NULL,
  motivo_perda_id bigint REFERENCES motivos_perda(id) ON DELETE SET NULL,
  changed_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_lead_history_lead ON lead_history (lead_id);

-- ============================================================================
-- AUDITORIA DE QUALIDADE
-- ============================================================================
CREATE TABLE upload_logs (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  filename     text,
  uploaded_by  uuid REFERENCES profiles(id) ON DELETE SET NULL,
  record_count integer DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE messages_logs (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  protocol           text,
  contact            text,
  agent_id           uuid REFERENCES profiles(id) ON DELETE SET NULL,
  agent_name         text,
  message_content    text,
  "timestamp"        timestamptz,
  has_empathy        boolean DEFAULT false,
  closing_attempt    boolean DEFAULT false,
  final_score        double precision,
  empathy_score      double precision DEFAULT 0,
  clarity_score      double precision DEFAULT 0,
  depth_score        double precision DEFAULT 0,
  commercial_score   double precision DEFAULT 0,
  agility_score      double precision DEFAULT 0,
  message_count      integer DEFAULT 0,
  upload_id          uuid REFERENCES upload_logs(id) ON DELETE SET NULL,
  status             text DEFAULT 'approved',
  is_commercial      boolean DEFAULT true,
  overall_conclusion text,
  improvements       text[],
  created_at         timestamptz NOT NULL DEFAULT timezone('utc', now())
);
CREATE INDEX idx_messages_logs_agent ON messages_logs (agent_name);
CREATE INDEX idx_messages_logs_ts    ON messages_logs ("timestamp");

-- ============================================================================
-- CONTEÚDO / CONFIG
-- ============================================================================
CREATE TABLE knowledge_base (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title      text,
  content    text,
  type       text DEFAULT 'document',
  category   text DEFAULT 'Geral',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE scripts (
  id          uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  titulo      text,
  categoria   text,
  curso       text,
  etapa_funil text,
  conteudo    text,
  ativo       boolean DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at  timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE financial_goals (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  year             integer,
  month            integer,
  monthly_target   numeric DEFAULT 0,
  monthly_achieved numeric DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_financial_goals_month ON financial_goals (year, month);

CREATE TABLE app_settings (
  key        text PRIMARY KEY,
  value      text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES profiles(id) ON DELETE SET NULL,
  action     text,
  details    jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_created ON audit_logs (created_at DESC);

-- ============================================================================
-- GESTÃO DE AGENTES  (módulo separado de profiles)
-- ============================================================================
CREATE TABLE agent_profiles (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name         text,
  photo_url    text,
  score_target numeric DEFAULT 8.0,
  role         text DEFAULT 'agent',
  email        text,
  phone        text,
  notes        text,
  active       boolean DEFAULT true,
  team_id      uuid REFERENCES teams(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_agent_profiles_name ON agent_profiles (name);

CREATE TABLE agent_reports (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name   text,
  year         integer,
  month        integer,
  share_token  text DEFAULT encode(extensions.gen_random_bytes(16), 'hex'),
  status       text DEFAULT 'draft',
  generated_at timestamptz NOT NULL DEFAULT now(),
  created_by   uuid REFERENCES profiles(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX idx_agent_reports_uniq ON agent_reports (agent_name, year, month);

-- ============================================================================
-- WIDECHAT (WhatsApp)
-- ============================================================================
CREATE TABLE widechat_messages (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id      integer REFERENCES leads(id) ON DELETE CASCADE,
  session_id   text,
  message_id   text,
  type         text DEFAULT 'text',
  message      text,
  origin       text,
  sender_name  text,
  raw_data     jsonb,
  created_at   timestamptz,
  processed_at timestamptz DEFAULT now()
);
CREATE INDEX idx_widechat_msg_lead    ON widechat_messages (lead_id);
CREATE INDEX idx_widechat_msg_created ON widechat_messages (created_at);
CREATE INDEX idx_widechat_msg_origin  ON widechat_messages (origin);

CREATE TABLE widechat_raw_messages (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id  text,
  origin      text,
  sender_name text,
  message     text,
  platform_id text,
  message_id  text,
  payload     jsonb,
  created_at  timestamptz,
  received_at timestamptz DEFAULT now()
);
CREATE INDEX idx_widechat_raw_platform ON widechat_raw_messages (platform_id);
CREATE INDEX idx_widechat_raw_created  ON widechat_raw_messages (created_at);
CREATE INDEX idx_widechat_raw_origin   ON widechat_raw_messages (origin);

CREATE TABLE widechat_atendimentos (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id          integer REFERENCES leads(id) ON DELETE CASCADE,
  protocol         text,
  widechat_agent_id text,
  session_id       text,
  contact_id       text,
  aceito_em        timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_widechat_atend_lead     ON widechat_atendimentos (lead_id);
CREATE INDEX idx_widechat_atend_protocol ON widechat_atendimentos (protocol);

CREATE TABLE widechat_webhook_logs (
  id         uuid PRIMARY KEY DEFAULT extensions.uuid_generate_v4(),
  payload    jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE user_integrations (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                   uuid REFERENCES profiles(id) ON DELETE CASCADE,
  widechat_email            text,
  widechat_password         text,
  widechat_session_token    text,
  widechat_token_expires_at timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_user_integrations_user ON user_integrations (user_id);

-- ============================================================================
-- META ADS / GOOGLE ADS
-- ============================================================================
CREATE TABLE meta_campaigns (
  campaign_id      text PRIMARY KEY,
  name             text,
  objective        text,
  status           text,
  daily_budget     numeric,
  lifetime_budget  numeric,
  budget_remaining numeric,
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE meta_campaign_insights_daily (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id   text,
  campaign_name text,
  date          date,
  spend         numeric DEFAULT 0,
  impressions   bigint DEFAULT 0,
  clicks        bigint DEFAULT 0,
  reach         bigint DEFAULT 0,
  frequency     numeric DEFAULT 0,
  ctr           numeric DEFAULT 0,
  cpm           numeric DEFAULT 0,
  leads_count   integer DEFAULT 0,
  actions_raw   jsonb,
  synced_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_meta_insights_camp_date ON meta_campaign_insights_daily (campaign_id, date);
CREATE UNIQUE INDEX idx_meta_insights_date ON meta_campaign_insights_daily (campaign_id, date);

CREATE TABLE meta_demographics_daily (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  date        date,
  age_range   text,
  gender      text,
  spend       numeric DEFAULT 0,
  impressions bigint DEFAULT 0,
  clicks      bigint DEFAULT 0,
  leads_count integer DEFAULT 0,
  synced_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_meta_demo_uniq ON meta_demographics_daily (date, age_range, gender);
CREATE INDEX idx_meta_demo_date ON meta_demographics_daily (date);

CREATE TABLE meta_account_stats (
  id             integer PRIMARY KEY DEFAULT 1,
  balance        numeric,
  currency       text,
  google_balance numeric,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT meta_account_stats_singleton CHECK (id = 1)
);

CREATE TABLE google_ads_campaigns (
  campaign_id              text PRIMARY KEY,
  campaign_name            text,
  status                   text,
  advertising_channel_type text,
  budget_amount            numeric,
  budget_type              text,
  synced_at                timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE google_ads_insights_daily (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id   text,
  campaign_name text,
  date          date,
  spend         numeric DEFAULT 0,
  impressions   bigint DEFAULT 0,
  clicks        bigint DEFAULT 0,
  conversions   numeric DEFAULT 0,
  synced_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_gads_camp_date ON google_ads_insights_daily (campaign_id, date);
CREATE INDEX idx_gads_date ON google_ads_insights_daily (date);

-- ============================================================================
-- SPONTE (ERP acadêmico)
-- ============================================================================
CREATE TABLE sponte_matriculas (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contrato_id            integer,
  aluno_id               integer,
  aluno                  text,
  turma_id               integer,
  nome_turma             text,
  nome_curso             text,
  curso_id               text,
  situacao_id            integer,
  situacao               text,
  data_matricula         date,
  data_inicio            date,
  data_termino           date,
  data_encerramento      date,
  contratante            text,
  numero_contrato        text,
  financeiro_lancado     text,
  nome_matriz_curricular text,
  tipo_contrato_id       integer,
  celular                text,
  synced_at              timestamptz NOT NULL DEFAULT now(),
  created_at             timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_sponte_curso ON sponte_matriculas (curso_id);
CREATE INDEX idx_sponte_data  ON sponte_matriculas (data_matricula);

CREATE TABLE sponte_parcelas (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conta_receber_id bigint,
  numero_parcela   text,
  aluno_id         integer,
  situacao_parcela text,
  data_pagamento   date,
  vencimento       date,
  valor_parcela    numeric,
  valor_pago       numeric,
  forma_cobranca   text,
  categoria        text,
  categoria_id     integer,
  sacado           text,
  conta_creditar   text,
  synced_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_sponte_parcelas_aluno ON sponte_parcelas (aluno_id);

-- matrículas (upload manual — módulo antigo, mantido)
CREATE TABLE matriculas (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cpf            text,
  nome           text,
  email          text,
  telefone       text,
  curso          text,
  turma          text,
  data_matricula date,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_matriculas_cpf  ON matriculas (cpf);
CREATE INDEX idx_matriculas_data ON matriculas (data_matricula);
CREATE TRIGGER trg_matriculas_updated_at BEFORE UPDATE ON matriculas
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================================
-- TICKETS (Central de Atendimento)
-- ============================================================================
CREATE TABLE tickets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protocolo      text NOT NULL UNIQUE,
  titulo         text NOT NULL,
  categoria      ticket_categoria NOT NULL,
  prioridade     ticket_prioridade NOT NULL DEFAULT 'media',
  status         ticket_status NOT NULL DEFAULT 'aberto',
  aluno_id       uuid NOT NULL REFERENCES auth.users(id),
  aluno_nome     text NOT NULL,
  aluno_email    text NOT NULL,
  atendente_id   uuid REFERENCES profiles(id) ON DELETE SET NULL,
  curso_id       integer REFERENCES courses(id) ON DELETE SET NULL,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  first_response_at timestamptz,
  resolved_at    timestamptz,
  avaliado       boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_tickets_aluno     ON tickets (aluno_id);
CREATE INDEX idx_tickets_atendente ON tickets (atendente_id);
CREATE INDEX idx_tickets_status    ON tickets (status);
CREATE INDEX idx_tickets_created   ON tickets (created_at DESC);
CREATE INDEX idx_tickets_protocolo ON tickets (protocolo);

CREATE OR REPLACE FUNCTION generate_ticket_protocolo() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE seq int;
BEGIN
  SELECT COUNT(*) + 1 INTO seq FROM tickets;
  NEW.protocolo := 'FICV-' || TO_CHAR(now(), 'YYYY') || '-' || LPAD(seq::text, 5, '0');
  RETURN NEW;
END $$;
CREATE TRIGGER trg_ticket_protocolo BEFORE INSERT ON tickets
  FOR EACH ROW WHEN (NEW.protocolo IS NULL OR NEW.protocolo = '')
  EXECUTE FUNCTION generate_ticket_protocolo();
CREATE TRIGGER trg_tickets_updated_at BEFORE UPDATE ON tickets
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE ticket_messages (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  bigint NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  autor_id   uuid NOT NULL REFERENCES auth.users(id),
  autor_nome text NOT NULL,
  autor_role text NOT NULL,
  conteudo   text NOT NULL,
  interno    boolean NOT NULL DEFAULT false,
  attachments jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_ticket_msg_ticket ON ticket_messages (ticket_id);

CREATE TABLE ticket_evaluations (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id     bigint NOT NULL UNIQUE REFERENCES tickets(id) ON DELETE CASCADE,
  aluno_id      uuid NOT NULL REFERENCES auth.users(id),
  csat_nota     smallint NOT NULL CHECK (csat_nota BETWEEN 1 AND 5),
  ces_nota      smallint NOT NULL CHECK (ces_nota BETWEEN 1 AND 7),
  fcr_resolvido boolean NOT NULL DEFAULT false,
  nps_nota      smallint CHECK (nps_nota BETWEEN 0 AND 10),
  comentario    text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_ticket_eval_ticket ON ticket_evaluations (ticket_id);

-- ============================================================================
-- PARTNERS / REFERRAL  (nasceram no SurrealDB)
-- ============================================================================
CREATE TABLE partners (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug       text,
  name       text,
  active     boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_partners_slug ON partners (slug);

CREATE TABLE referral_clicks (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_id uuid REFERENCES partners(id) ON DELETE SET NULL,
  ip         text,
  user_agent text,
  referrer   text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_referral_partner ON referral_clicks (partner_id);

CREATE TABLE sendpulse_forms (
  book_id       bigint PRIMARY KEY,
  form_name     text,
  course_id     integer REFERENCES courses(id) ON DELETE SET NULL,
  source_id     bigint REFERENCES lead_sources(id) ON DELETE SET NULL,
  ativo         boolean DEFAULT true,
  last_add_date text,
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_sendpulse_forms_book ON sendpulse_forms (book_id);

CREATE TABLE sendpulse_webhook_logs (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  payload    jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
