-- Bug: generate_ticket_protocolo() usava `SELECT COUNT(*)+1 FROM tickets` como se fosse uma
-- sequência. Isso é racy — dois inserts simultâneos (ex: duplo clique em "Abrir ticket") leem o
-- mesmo COUNT(*) antes de qualquer um comitar, calculam o MESMO protocolo, e o segundo insert
-- estoura "duplicate key value violates unique constraint tickets_protocolo_key". Também quebraria
-- silenciosamente se algum ticket fosse deletado (reaproveitaria número já usado).
--
-- Fix: usa NEW.id em vez de COUNT(*). `id` é `GENERATED BY DEFAULT AS IDENTITY` — já vem de uma
-- sequência atômica do Postgres, preenchida ANTES do trigger BEFORE INSERT rodar, então é
-- garantidamente único mesmo sob concorrência, sem precisar de lock nem de nova tabela.
CREATE OR REPLACE FUNCTION generate_ticket_protocolo() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.protocolo := 'FICV-' || TO_CHAR(now(), 'YYYY') || '-' || LPAD(NEW.id::text, 5, '0');
  RETURN NEW;
END $$;
