-- ============================================================================
-- Atendimento do aluno: funções + filas (decisões do usuário 25/09).
--
-- Funções novas em profiles.role (só enxergam CHAMADOS — nada do CRM de vendas):
--   secretaria  → vê os chamados das filas de que é membro (+ os atribuídos a ele)
--   tutor       → idem (ex.: tutor só de Pós é membro só da fila "Tutoria Pós")
--   coordenador → vê TODAS as filas
-- admin/agent continuam como antes (is_staff).
--
-- Filas: cada fila = nível (graduação/pós/todos) × assuntos (categorias) × membros.
-- Chamado novo cai na fila pelo gatilho: acadêmico → Tutoria do nível do aluno;
-- o resto → Secretaria (fila padrão, que também pega o que não casar com nada).
-- Nível do aluno: curso do chamado (courses.type) ou alunos.nivel (vem do Sponte).
-- ============================================================================

-- ── papéis ──────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.my_role() RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT role FROM profiles WHERE id = auth.uid();
$$;
CREATE OR REPLACE FUNCTION public.is_ticket_staff() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid()
                 AND role IN ('admin','agent','secretaria','tutor','coordenador'));
$$;

-- ── filas ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ticket_queues (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        text NOT NULL,
  nivel       text NOT NULL DEFAULT 'todos' CHECK (nivel IN ('todos','graduacao','pos')),
  categorias  ticket_categoria[] NOT NULL DEFAULT '{}',
  padrao      boolean NOT NULL DEFAULT false,   -- recebe o que não casar com nenhuma fila
  ativo       boolean NOT NULL DEFAULT true,
  ordem       integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ticket_queue_members (
  queue_id    bigint NOT NULL REFERENCES ticket_queues(id) ON DELETE CASCADE,
  profile_id  uuid   NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  PRIMARY KEY (queue_id, profile_id)
);

INSERT INTO ticket_queues (nome, nivel, categorias, padrao, ordem)
SELECT * FROM (VALUES
  ('Secretaria', 'todos', '{secretaria,certificado,cancelamento,financeiro,suporte_tecnico,outros}'::ticket_categoria[], true, 1),
  ('Tutoria — Graduação', 'graduacao', '{academico}'::ticket_categoria[], false, 2),
  ('Tutoria — Pós-graduação', 'pos', '{academico}'::ticket_categoria[], false, 3)
) v(nome, nivel, categorias, padrao, ordem)
WHERE NOT EXISTS (SELECT 1 FROM ticket_queues);

ALTER TABLE tickets ADD COLUMN IF NOT EXISTS queue_id bigint REFERENCES ticket_queues(id) ON DELETE SET NULL;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS nivel text CHECK (nivel IN ('graduacao','pos'));
ALTER TABLE alunos  ADD COLUMN IF NOT EXISTS nivel text CHECK (nivel IN ('graduacao','pos'));
CREATE INDEX IF NOT EXISTS idx_tickets_queue ON tickets (queue_id);

-- ── visibilidade ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.ticket_visible(p_queue bigint, p_atendente uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT CASE my_role()
    WHEN 'admin' THEN true
    WHEN 'agent' THEN true
    WHEN 'coordenador' THEN true
    WHEN 'secretaria' THEN p_atendente = auth.uid()
         OR EXISTS (SELECT 1 FROM ticket_queue_members m WHERE m.queue_id = p_queue AND m.profile_id = auth.uid())
    WHEN 'tutor' THEN p_atendente = auth.uid()
         OR EXISTS (SELECT 1 FROM ticket_queue_members m WHERE m.queue_id = p_queue AND m.profile_id = auth.uid())
    ELSE false END;
$$;

DROP POLICY IF EXISTS tickets_select ON tickets;
DROP POLICY IF EXISTS tickets_update ON tickets;
CREATE POLICY tickets_select ON tickets FOR SELECT USING (aluno_id = auth.uid() OR public.ticket_visible(queue_id, atendente_id));
CREATE POLICY tickets_update ON tickets FOR UPDATE USING (aluno_id = auth.uid() OR public.ticket_visible(queue_id, atendente_id));

DROP POLICY IF EXISTS tmsg_select ON ticket_messages;
CREATE POLICY tmsg_select ON ticket_messages FOR SELECT USING (
  EXISTS (SELECT 1 FROM tickets t WHERE t.id = ticket_messages.ticket_id
          AND ((t.aluno_id = auth.uid() AND ticket_messages.interno = false)
               OR public.ticket_visible(t.queue_id, t.atendente_id))));

DROP POLICY IF EXISTS teval_select ON ticket_evaluations;
CREATE POLICY teval_select ON ticket_evaluations FOR SELECT USING (aluno_id = auth.uid() OR public.is_ticket_staff());

-- o que as funções de atendimento precisam ler fora dos chamados
DROP POLICY IF EXISTS alunos_staff_all ON alunos;
CREATE POLICY alunos_staff_all ON alunos FOR SELECT USING (public.is_ticket_staff());
DROP POLICY IF EXISTS alunos_self_upd ON alunos;
CREATE POLICY alunos_self_upd ON alunos FOR UPDATE USING (id = auth.uid() OR public.is_ticket_staff());
DROP POLICY IF EXISTS courses_sel ON courses;
CREATE POLICY courses_sel ON courses FOR SELECT USING (public.is_ticket_staff() OR auth.role() = 'authenticated');
DROP POLICY IF EXISTS profiles_sel ON profiles;
CREATE POLICY profiles_sel ON profiles FOR SELECT USING (public.is_ticket_staff() OR id = auth.uid());
DROP POLICY IF EXISTS quick_replies_staff_select ON quick_replies;
CREATE POLICY quick_replies_staff_select ON quick_replies FOR SELECT USING (public.is_ticket_staff());

ALTER TABLE ticket_queues ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_queue_members ENABLE ROW LEVEL SECURITY;
CREATE POLICY ticket_queues_sel ON ticket_queues FOR SELECT USING (public.is_ticket_staff());
CREATE POLICY ticket_queues_admin ON ticket_queues FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY ticket_queue_members_sel ON ticket_queue_members FOR SELECT USING (public.is_ticket_staff());
CREATE POLICY ticket_queue_members_admin ON ticket_queue_members FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- ── roteamento ──────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.ticket_route(p_categoria ticket_categoria, p_nivel text) RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM (
    SELECT id, 0 AS prio, ordem FROM ticket_queues
     WHERE ativo AND p_categoria = ANY(categorias) AND nivel = p_nivel
    UNION ALL
    SELECT id, 1, ordem FROM ticket_queues
     WHERE ativo AND p_categoria = ANY(categorias) AND nivel = 'todos'
    UNION ALL
    SELECT id, 2, ordem FROM ticket_queues WHERE ativo AND padrao
  ) q ORDER BY prio, ordem LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.ticket_set_queue() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.nivel IS NULL THEN
    SELECT CASE WHEN c.type ILIKE 'p%s%' THEN 'pos' WHEN c.type ILIKE 'gradua%' THEN 'graduacao' END
      INTO NEW.nivel FROM courses c WHERE c.id = NEW.curso_id;
    IF NEW.nivel IS NULL AND NEW.aluno_id IS NOT NULL THEN
      SELECT nivel INTO NEW.nivel FROM alunos WHERE id = NEW.aluno_id;
    END IF;
  END IF;
  IF NEW.queue_id IS NULL OR (TG_OP = 'UPDATE' AND NEW.categoria IS DISTINCT FROM OLD.categoria AND NEW.queue_id IS NOT DISTINCT FROM OLD.queue_id) THEN
    NEW.queue_id := public.ticket_route(NEW.categoria, NEW.nivel);
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_ticket_set_queue ON tickets;
CREATE TRIGGER trg_ticket_set_queue BEFORE INSERT OR UPDATE OF categoria ON tickets
  FOR EACH ROW EXECUTE FUNCTION public.ticket_set_queue();

-- chamados já existentes
UPDATE tickets SET queue_id = public.ticket_route(categoria, nivel) WHERE queue_id IS NULL;
