-- ============================================================================
-- Hub do Grupo Cidade Viva (26/09) — o número oficial 83 3041-7471 (antes no WideChat)
-- é usado por todo o grupo (Faculdade, Igreja, Escola, Education, Fundação...). Cada
-- empresa vai ganhar número próprio; enquanto isso, quem escrever no número antigo:
--   · já é da Faculdade (aluno/lead) → fluxo normal (portal / IA de vendas);
--   · contato novo → IA classifica o assunto → Faculdade fica aqui (Híbrido, sem custo
--     Meta); outra empresa → recebe o número novo + link, e o canal da empresa (se
--     cadastrado) já chama a pessoa; sem assunto claro → menu numerado.
-- ============================================================================

-- canal: "hub" (roteia o grupo) e canais de OUTRAS empresas do grupo (só pra o hub avisar)
ALTER TABLE vivaconnect_channels ADD COLUMN IF NOT EXISTS hub_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE vivaconnect_channels DROP CONSTRAINT IF EXISTS vivaconnect_channels_purpose_check;
ALTER TABLE vivaconnect_channels ADD CONSTRAINT vivaconnect_channels_purpose_check CHECK (purpose IN ('official', 'pool', 'grupo'));

ALTER TABLE vivaconnect_outbox DROP CONSTRAINT IF EXISTS vivaconnect_outbox_kind_check;
ALTER TABLE vivaconnect_outbox ADD CONSTRAINT vivaconnect_outbox_kind_check
  CHECK (kind IN ('first_message', 'student_reply', 'ai_reply', 'manual', 'hub_menu', 'hub_redirect', 'hub_forward'));

-- textos do hub
ALTER TABLE vivaconnect_settings
  ADD COLUMN IF NOT EXISTS hub_menu_template text NOT NULL DEFAULT
    E'Olá{nome_virgula}! 👋 Você falou com o atendimento do *Grupo Cidade Viva*.\nPara te direcionar certinho, com quem você quer falar? Responda com o número:\n\n{opcoes}',
  ADD COLUMN IF NOT EXISTS hub_max_menus integer NOT NULL DEFAULT 2;

-- destinos (empresas do grupo). is_self = a própria Faculdade (fica neste número).
CREATE TABLE IF NOT EXISTS vivaconnect_hub_destinations (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            text NOT NULL,
  emoji           text NOT NULL DEFAULT '🏢',
  assuntos        text NOT NULL DEFAULT '',          -- o que é dessa empresa (a IA lê isto)
  is_self         boolean NOT NULL DEFAULT false,
  numero          text,                              -- número novo (dígitos, 55DDD...)
  channel_id      bigint REFERENCES vivaconnect_channels(id) ON DELETE SET NULL, -- canal Z-PRO da empresa
  avisar_destino  boolean NOT NULL DEFAULT true,     -- o canal da empresa já chama a pessoa
  mensagem_redirect text NOT NULL DEFAULT
    E'Olá{nome_virgula}! 💙 O atendimento da *{empresa}* agora tem um número exclusivo: *{numero}*.\nÉ só tocar aqui para falar com a equipe: {link}\n\nSalve o novo contato! 😉',
  mensagem_destino text NOT NULL DEFAULT
    E'Olá{nome_virgula}! Aqui é da *{empresa}* 💙 Você nos procurou pelo número antigo do Grupo Cidade Viva: "{mensagem}". A partir de agora, falamos por aqui. Como podemos te ajudar?',
  ativo           boolean NOT NULL DEFAULT true,
  ordem           integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS vivaconnect_hub_destinations_one_self ON vivaconnect_hub_destinations (is_self) WHERE is_self;

-- cada contato que passou pelo hub (sessão + histórico do direcionamento)
CREATE TABLE IF NOT EXISTS vivaconnect_hub_routings (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id      bigint REFERENCES vivaconnect_channels(id) ON DELETE SET NULL,
  number          text NOT NULL,
  contact_name    text,
  status          text NOT NULL DEFAULT 'perguntando' CHECK (status IN ('perguntando', 'faculdade', 'encaminhado')),
  destination_id  bigint REFERENCES vivaconnect_hub_destinations(id) ON DELETE SET NULL,
  metodo          text,                               -- ia | menu | fallback
  confianca       numeric,
  motivo          text,
  menus           integer NOT NULL DEFAULT 0,
  messages        jsonb NOT NULL DEFAULT '[]',        -- [{de:'contato'|'hub', texto, em}]
  lead_id         bigint REFERENCES leads(id) ON DELETE SET NULL,
  redirected_at   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS vivaconnect_hub_routings_number ON vivaconnect_hub_routings (number, updated_at DESC);
CREATE INDEX IF NOT EXISTS vivaconnect_hub_routings_created ON vivaconnect_hub_routings (created_at DESC);

ALTER TABLE vivaconnect_hub_destinations ENABLE ROW LEVEL SECURITY;
ALTER TABLE vivaconnect_hub_routings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hub_dest_admin ON vivaconnect_hub_destinations;
CREATE POLICY hub_dest_admin ON vivaconnect_hub_destinations FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS hub_rout_admin ON vivaconnect_hub_routings;
CREATE POLICY hub_rout_admin ON vivaconnect_hub_routings FOR SELECT USING (public.is_admin());

-- destinos iniciais: só a Faculdade ativa; as outras empresas ficam desligadas até
-- terem número (Gestão > VivaConnect > Hub do Grupo).
INSERT INTO vivaconnect_hub_destinations (nome, emoji, assuntos, is_self, ativo, ordem)
SELECT * FROM (VALUES
  ('Faculdade Internacional Cidade Viva (FICV)', '🎓',
   'Faculdade / ensino superior: vestibular, graduação (Teologia, Direito), pós-graduação, cursos da faculdade, matrícula na faculdade, mensalidade da faculdade, bolsas, portal do aluno, diploma, certificado, secretaria acadêmica, tutoria, biblioteca.',
   true, true, 1),
  ('Igreja Cidade Viva', '⛪',
   'Igreja: como se tornar membro, membresia, cultos e horários, batismo, células/pequenos grupos, aconselhamento pastoral, oração, casamento na igreja, apresentação de crianças, ministérios, dízimos e ofertas, eventos e conferências da igreja.',
   false, false, 2),
  ('Escola Cidade Viva', '🏫',
   'Escola (educação básica): educação infantil, ensino fundamental, ensino médio, matrícula/rematrícula escolar, vagas, mensalidade da escola, material escolar, uniforme, horário das aulas, boletim de filho, reunião de pais.',
   false, false, 3),
  ('Cidade Viva Education', '💻',
   'Cidade Viva Education: (descreva aqui os assuntos — ex.: cursos livres, plataforma de cursos online, assinaturas).',
   false, false, 4),
  ('Fundação Cidade Viva', '🤝',
   'Fundação: projetos sociais, ação social, doações para projetos, voluntariado, parcerias sociais, atendimento comunitário.',
   false, false, 5)
) v(nome, emoji, assuntos, is_self, ativo, ordem)
WHERE NOT EXISTS (SELECT 1 FROM vivaconnect_hub_destinations);

-- a view de saúde dos canais passa a mostrar hub_enabled
CREATE OR REPLACE VIEW vivaconnect_channel_health AS
 SELECT id, name, purpose, kind, phone, api_id, zpro_whatsapp_id, active, daily_limit, last_sent_at, last_ok_at, last_error, last_error_at, created_at,
    (( SELECT count(*) FROM vivaconnect_outbox o
          WHERE o.channel_id = c.id AND o.status = 'sent' AND o.kind = 'first_message'
            AND o.sent_at >= (date_trunc('day', now() AT TIME ZONE 'America/Sao_Paulo') AT TIME ZONE 'America/Sao_Paulo')))::integer AS first_sent_today,
    (( SELECT count(*) FROM vivaconnect_outbox o
          WHERE o.channel_id = c.id AND o.status = 'failed' AND o.created_at > now() - interval '24 hours'))::integer AS failed_24h,
    (( SELECT count(*) FROM leads l WHERE l.vivaconnect_channel_id = c.id))::integer AS leads_fixed,
    (api_token IS NOT NULL AND api_token <> '') AS has_token,
    ai_enabled,
    hub_enabled
   FROM vivaconnect_channels c
  WHERE is_admin() OR COALESCE(auth.role(), '') = 'service_role' OR CURRENT_USER = ANY (ARRAY['postgres'::name, 'service_role'::name]);

-- trava por contato: o hub trata UMA mensagem por vez do mesmo número ("Oi" + "quero ser
-- membro" em sequência viram uma fala só, em vez de menu + encaminhamento)
CREATE TABLE IF NOT EXISTS vivaconnect_hub_locks (number text PRIMARY KEY, locked_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE vivaconnect_hub_locks ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION public.hub_try_lock(p_number text) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE ok boolean;
BEGIN
  DELETE FROM vivaconnect_hub_locks WHERE number = p_number AND locked_at < now() - interval '60 seconds';
  INSERT INTO vivaconnect_hub_locks (number) VALUES (p_number) ON CONFLICT DO NOTHING RETURNING true INTO ok;
  RETURN coalesce(ok, false);
END $$;
REVOKE EXECUTE ON FUNCTION public.hub_try_lock(text) FROM PUBLIC, anon, authenticated;
