-- ============================================================================
-- Portal do Aluno (/aluno): conta ligada ao Sponte + e-mails dos chamados (Resend).
--
-- alunos: sponte_aluno_id (GetAlunos CPF=…), must_change_password (1º acesso é
-- CPF/CPF como no Sponte → o portal obriga a trocar), dados de contato do Sponte.
--
-- ticket_email_outbox: fila de e-mails pro aluno, preenchida por gatilhos e
-- enviada pela edge function ticket-emails (cron 1/min):
--   created  → aluno abriu o chamado (na hora)
--   reply    → atendente respondeu (espera 5 min pra agrupar; 1 pendente por chamado)
--   resolved → chamado resolvido
--   reminder → "aguardando você" há 48h (gerado pela própria function)
-- ============================================================================

ALTER TABLE alunos
  ADD COLUMN IF NOT EXISTS sponte_aluno_id      integer,
  ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS telefone             text,
  ADD COLUMN IF NOT EXISTS ra                   text,
  ADD COLUMN IF NOT EXISTS last_login_at        timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS uq_alunos_cpf_digits ON alunos (regexp_replace(cpf, '\D', '', 'g'));

-- tentativas de 1º acesso / esqueci a senha (limite por CPF)
CREATE TABLE IF NOT EXISTS aluno_auth_attempts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf        text NOT NULL,
  action     text NOT NULL,
  ok         boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aluno_auth_attempts ON aluno_auth_attempts (cpf, created_at DESC);
ALTER TABLE aluno_auth_attempts ENABLE ROW LEVEL SECURITY;  -- só service_role

-- ── fila de e-mails ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ticket_email_outbox (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id     bigint NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  kind          text NOT NULL CHECK (kind IN ('created','reply','resolved','reminder')),
  status        text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','skipped','failed')),
  scheduled_at  timestamptz NOT NULL DEFAULT now(),
  sent_at       timestamptz,
  to_email      text,
  error         text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ticket_email_due ON ticket_email_outbox (scheduled_at) WHERE status = 'pending';
-- no máximo 1 e-mail pendente de cada tipo por chamado (respostas seguidas viram 1 e-mail)
CREATE UNIQUE INDEX IF NOT EXISTS uq_ticket_email_pending ON ticket_email_outbox (ticket_id, kind) WHERE status = 'pending';
ALTER TABLE ticket_email_outbox ENABLE ROW LEVEL SECURITY;
CREATE POLICY ticket_email_outbox_staff ON ticket_email_outbox FOR SELECT USING (public.is_staff());

-- chamado aberto pelo aluno → confirmação
CREATE OR REPLACE FUNCTION public.ticket_email_on_ticket() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.aluno_id IS NOT NULL THEN
      INSERT INTO ticket_email_outbox (ticket_id, kind) VALUES (NEW.id, 'created') ON CONFLICT DO NOTHING;
    END IF;
  ELSIF NEW.status = 'resolvido' AND OLD.status IS DISTINCT FROM 'resolvido' THEN
    INSERT INTO ticket_email_outbox (ticket_id, kind, scheduled_at)
    VALUES (NEW.id, 'resolved', now() + interval '5 minutes') ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_ticket_email_on_ticket ON tickets;
CREATE TRIGGER trg_ticket_email_on_ticket AFTER INSERT OR UPDATE OF status ON tickets
  FOR EACH ROW EXECUTE FUNCTION public.ticket_email_on_ticket();

-- resposta pública do atendimento → aviso (agrupado: 5 min depois da 1ª resposta,
-- e nunca menos de 15 min depois do último aviso desse chamado)
CREATE OR REPLACE FUNCTION public.ticket_email_on_message() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE last_sent timestamptz;
BEGIN
  IF NEW.autor_role = 'aluno' OR coalesce(NEW.interno, false) THEN RETURN NEW; END IF;
  SELECT max(sent_at) INTO last_sent FROM ticket_email_outbox
   WHERE ticket_id = NEW.ticket_id AND kind = 'reply' AND status = 'sent';
  INSERT INTO ticket_email_outbox (ticket_id, kind, scheduled_at)
  VALUES (NEW.ticket_id, 'reply', greatest(now() + interval '5 minutes', coalesce(last_sent + interval '15 minutes', now())))
  ON CONFLICT DO NOTHING;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_ticket_email_on_message ON ticket_messages;
CREATE TRIGGER trg_ticket_email_on_message AFTER INSERT ON ticket_messages
  FOR EACH ROW EXECUTE FUNCTION public.ticket_email_on_message();

-- worker (1/min), mesmo header de auth do cron do SendPulse
DO $$
DECLARE auth text;
BEGIN
  SELECT substring(command from 'Bearer [A-Za-z0-9._-]+') INTO auth FROM cron.job WHERE jobname = 'sync-sendpulse-forms';
  PERFORM cron.unschedule('ticket-emails') WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname='ticket-emails');
  PERFORM cron.schedule('ticket-emails', '* * * * *', format(
    $c$SELECT net.http_post(url := 'https://jsswkmybkgoxpncnxgdd.supabase.co/functions/v1/ticket-emails', headers := jsonb_build_object('Content-Type','application/json','Authorization',%L), body := '{}'::jsonb, timeout_milliseconds := 55000)$c$, auth));
END $$;
